# Generated by Django 4.2 on 2023-05-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('company_name', models.CharField(max_length=100, verbose_name='Компания')),
                ('position_name', models.CharField(max_length=100, verbose_name='Должность')),
                ('hire_date', models.DateField(verbose_name='Дата приема')),
                ('fire_date', models.DateField(null=True, verbose_name='Дата увольнения')),
                ('salary', models.IntegerField(verbose_name='Ставка, руб')),
                ('fraction', models.IntegerField(verbose_name='Ставка, %')),
                ('base', models.IntegerField(verbose_name='База')),
                ('advance', models.IntegerField(verbose_name='Аванс')),
                ('by_hours', models.BooleanField(verbose_name='Почасовая оплата')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
    ]
